# Generated by Django 5.1.15 on 2026-10-06 15:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def dedupe_invoice_provider_ids(apps, schema_editor):
    """Make pre-existing duplicate payment/order ids unique so the new constraints can be added."""
    Invoice = apps.get_model("billing", "Invoice")
    for field in ("provider_payment_id", "provider_invoice_id"):
        seen = set()
        for inv in Invoice.objects.exclude(**{field: ""}).order_by("issued_at", "id"):
            value = getattr(inv, field)
            if value in seen:
                setattr(inv, field, f"{value}-dup-{str(inv.id)[:8]}")
                inv.save(update_fields=[field])
            else:
                seen.add(value)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_invoice_provider_ids, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_interval', models.CharField(default='monthly', max_length=20)),
                ('provider_order_id', models.CharField(max_length=255, unique=True)),
                ('amount_paise', models.BigIntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('abandoned', 'Abandoned')], default='created', max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('extended', 'Extended by Admin'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('grace_period', 'Grace Period (90 days)'), ('expired', 'Expired (90-Day Retention)'), ('suspended', 'Suspended'), ('purged', 'Data Purged (90-Day Lapsed)'), ('canceled', 'Canceled')], default='active', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider_payment_id',), name='uniq_invoice_provider_payment_id'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_invoice_id', ''), _negated=True), fields=('provider_invoice_id',), name='uniq_invoice_provider_order_id'),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_orders', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='checkoutorder',
            index=models.Index(fields=['user', 'plan', 'billing_interval', 'status'], name='billing_che_user_id_b3c331_idx'),
        ),
    ]
