# Generated by Django 5.1.15 on 2026-09-05 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='storage_quota', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bytes_used', models.BigIntegerField(default=0)),
                ('bytes_limit', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], max_length=10)),
                ('encrypted_name', models.TextField()),
                ('name_nonce', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('thumbnail_object_key', models.CharField(blank=True, default='', max_length=255)),
                ('thumbnail_nonce', models.CharField(blank=True, default='', max_length=64)),
                ('trashed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.node')),
            ],
            options={
                'ordering': ['type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.IntegerField(default=1)),
                ('object_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('size_bytes', models.BigIntegerField()),
                ('wrapped_file_key', models.TextField()),
                ('content_nonce', models.CharField(max_length=64)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='storage.node')),
            ],
            options={
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('upload_id', models.CharField(db_index=True, max_length=255)),
                ('object_key', models.CharField(max_length=255, unique=True)),
                ('encrypted_name', models.TextField()),
                ('name_nonce', models.CharField(max_length=64)),
                ('expected_size_bytes', models.BigIntegerField()),
                ('part_size', models.IntegerField(default=8388608)),
                ('parts', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='initiated', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_uploads', to='storage.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['owner', 'parent', 'trashed_at', 'deleted_at'], name='storage_nod_owner_i_6af615_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileversion',
            unique_together={('node', 'version_no')},
        ),
    ]
